# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

# ======================= JOBS =======================
jobs:
  gapic-generator-java-tests:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/project/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Build targets
          command: |
            bazel build //...
      - run:
          name: Test targets
          command: |
            bazel test //...
  google-java-format:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/workspace/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Java Linter
          command: |
            bazel build //:google_java_format_verification
  license-header:
    docker:
      -image: circleci/golang:1.13
    working_directory: /home/circleci/workspace/gapic-generator-java
    steps:
      - checkout
      - run:
          name: License Header
          command: |
            go get -u github.com/google/addlicense
            addlicense -c "Google LLC" -l apache .
# ======================= WORKFLOWS =======================

workflows:
  version: 2
  run_tests:
    jobs:
      - gapic-generator-java-tests
      - google-java-format
      - license-header
