version: 2.1

# ======================= JOBS =======================
jobs:
  gapic-generator-java-tests:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/project/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Builder
          command: |
            bazel build //...
  google-java-format:
    docker:
      - image: l.gcr.io/google/bazel
    steps:
      - attach_workspace:
          at: /home/circleci/workspace
      - run:
          name: Java Linter
          command: |
            bazel run //:google_java_format_verification

# ======================= WORKFLOWS =======================

workflows:
  version: 2
  run_tests:
    jobs:
      - gapic-generator-java-tests
      - google-java-format:
          requires:
            - gapic-generator-java-tests
