on:
  push:
    branches:
      - main
  pull_request:
name: ci-maven
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - run: java -version

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit Tests
        run: |
          mvn verify --batch-mode --no-transfer-progress -Dcheckstyle.skip

  units-java8:
    name: "units (8)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Java 8 tests uses JDK 11 to compile and JDK 8 to run tests.
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      - name: Compile with Java 11
        shell: bash
        run: |
          set -x
          export JAVA_HOME=$JAVA11_HOME
          export PATH=${JAVA_HOME}/bin:$PATH

          # Why not compile? It's because the process needs to package jar so
          # that gapic-generator-java module can use testlib modules of gax.
          mvn verify --batch-mode --no-transfer-progress -Dcheckstyle.skip  -DskipTests
      - name: Run test with Java 8
        shell: bash
        run: |
          set -x
          export JAVA_HOME=$JAVA8_HOME
          export PATH=${JAVA_HOME}/bin:$PATH
          # useIncrementalCompilation not to recompile previous class file
          mvn test --batch-mode --no-transfer-progress \
              -Dcheckstyle.skip -DuseIncrementalCompilation=false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - run: java -version
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Java Linter
        run: mvn fmt:check
        working-directory: gapic-generator-java